# Generated by Django 5.0.6 on 2024-06-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_booking_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Members',
        ),
    ]
