# Generated by Django 5.0.6 on 2024-06-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_members_alter_booking_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='roomid',
        ),
        migrations.AddField(
            model_name='members',
            name='expiry',
            field=models.DateField(null=True, verbose_name='expiry'),
        ),
    ]
